### ISSUE TITLE
Error on gencode22 GTF

### ISSUE THREAD

**Issue by jonearls** [MuhammedHasan/gencode_utr_fix#1]
Hello,

I've been trying out your tool.  It worked as expected on `gencode.v29.annotation.gtf`.

But when I tried the same thing on `gencode.v22.annotation.gtf` --downloaded directly from Gencode's website-- I got the following error:

gencode_utr_fix --input_gtf gencode.v22.annotation.gtf --output_gtf gencode.v22.annotation_utr.gtf
Reading GTF...
Calculating CDS locations...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 198442/198442 [02:32<00:00, 1305.15it/s]
Calculating UTR side...
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/bin/gencode_utr_fix", line 33, in <module>
    sys.exit(load_entry_point('gencode-utr-fix', 'console_scripts', 'gencode_utr_fix')())
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/docker_scratch/gtf_fun/src/gencode-utr-fix/gencode_utr_fix/main.py", line 74, in cli
    gr_utr = gencode_utr_fix(gr)
  File "/docker_scratch/gtf_fun/src/gencode-utr-fix/gencode_utr_fix/main.py", line 65, in gencode_utr_fix
    return gr.apply(lambda df: df.apply(update_utr_row, axis=1))
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pyranges/pyranges.py", line 591, in apply
    result = pyrange_apply_single(f, self, **kwargs)
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pyranges/multithreaded.py", line 348, in pyrange_apply_single
    result = call_f_single(function, nparams, df, **kwargs)
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pyranges/multithreaded.py", line 33, in call_f_single
    return f.remote(df)
  File "/docker_scratch/gtf_fun/src/gencode-utr-fix/gencode_utr_fix/main.py", line 65, in <lambda>
    return gr.apply(lambda df: df.apply(update_utr_row, axis=1))
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/ec2-user/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/docker_scratch/gtf_fun/src/gencode-utr-fix/gencode_utr_fix/main.py", line 32, in __call__
    cds_start = self.starts[row['transcript_id']]
KeyError: 'ENST00000628927.1'

Are you aware of this issue? Is there a work around for it?

**Comment by jonearls** [comment]
Update: I tried filtering out the ens id that got the error and running again.  Then I got the same error on another ens id (ENST00000628076.1).  

Both of the error producing ens ids were of gene_type "IG_V_gene".

Next I tried filtering the gtf for "protein_coding" genes and re-ran.  This time there were no errors.  So I guess there is something off about (at least one of) the non protein_coding gene_types in older versions of gencode?  Weird.

Thank you for making this tool btw.
